version: 0.2

phases:
    install:
      runtime-versions:
        java: corretto11
      commands:
        - echo no commands yet
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - echo Build started on `date`
        - npm run webpack
    post_build:
      commands:
        - echo no commands here
artifacts:
  files:
    - index.html
    - favicon.ico
    - Shweta Mandavgane-Resume.pdf
    - styles/*
    - images/*
    - dist/*
